remote_theme: vChewing/jekyll-theme-read-the-docs
title: [vChewing 唯音]
description: [恐怕是 截至目前為止 在功能性方面 最強的 第三方免費 macOS 系統專用輸入法]
show_downloads: false
github:
  is_project_page: false
  repository_url: https://github.com/vChewing/vChewing-macOS/
readme_index:
  with_frontmatter: true
show_sorted: false
